# =============================================================================
# ShowSync Development Environment Configuration
# =============================================================================
# Development configuration with H2 database for local testing
# =============================================================================

spring:
  # Database configuration
  datasource:
    url: jdbc:h2:mem:showsync;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  # H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA configuration for development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Disable cache for development
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  # Disable external dependencies for dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
  
  # Disable Flyway for now (using JPA schema generation)
  flyway:
    enabled: false

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  # Development port
  port: 8080

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  # Enhanced logging levels for development
  level:
    # Root level
    root: INFO
    
    # ShowSync application - DEBUG level for detailed logging
    com.showsync: DEBUG
    
    # Spring framework
    org.springframework: INFO
    org.springframework.web: DEBUG

# =============================================================================
# ACTUATOR CONFIGURATION
# =============================================================================
management:
  # Expose basic actuator endpoints
  endpoints:
    web:
      exposure:
        include: "health,info"
  
  # Health check configuration
  endpoint:
    health:
      # Show basic health details
      show-details: always

# =============================================================================
# EXTERNAL API CONFIGURATION - DEVELOPMENT
# =============================================================================
external-apis:
  # TMDb API Configuration for development
  tmdb:
    # API Key for development environment
    # Set this as an environment variable: TMDB_API_KEY=your-actual-key
    # For local development, you can also create a .env file (add to .gitignore)
    apiKey: ${TMDB_API_KEY:your-tmdb-api-key-here}

# =============================================================================
# APPLICATION-SPECIFIC DEVELOPMENT SETTINGS
# =============================================================================
showsync:
  # Development-specific settings
  development:
    # Enable test data creation
    create-test-data: false
    # Enable mock external APIs
    mock-external-apis: true
    # Enhanced error messages
    detailed-error-messages: true 