# =============================================================================
# ShowSync Development Environment Configuration
# =============================================================================
# Development configuration with H2 database for local testing
# =============================================================================

spring:
  # Database configuration - H2 for quick development
  # To use PostgreSQL instead, uncomment the PostgreSQL section and comment out H2
  datasource:
    url: jdbc:h2:mem:showsync;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
    # PostgreSQL option for development (requires Docker services running)
    # url: jdbc:postgresql://localhost:5432/showsync_dev
    # driverClassName: org.postgresql.Driver
    # username: showsync_user
    # password: showsync_dev_password
  
  # H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA configuration for development
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Disable cache for development
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  # Disable external dependencies for dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
  
  # Enable Flyway for development (use proper database migrations)
  flyway:
    enabled: true
    # Clean database on startup in development for fresh schema
    clean-disabled: false

  # Security configuration for development
  security:
    jwt:
      secret: ${JWT_SECRET:ZGV2LXNlY3JldC1rZXktZm9yLWxvY2FsLWRldmVsb3BtZW50LW9ubHktbm90LWZvci1wcm9kdWN0aW9u}
      expiration: ${JWT_EXPIRATION:86400000}  # 24 hours
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  # Development port
  port: 8080

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  # Enhanced logging levels for development
  level:
    # Root level
    root: INFO
    
    # ShowSync application - DEBUG level for detailed logging
    com.showsync: DEBUG
    
    # Spring framework
    org.springframework: INFO
    org.springframework.web: DEBUG

# =============================================================================
# ACTUATOR CONFIGURATION
# =============================================================================
management:
  # Expose basic actuator endpoints
  endpoints:
    web:
      exposure:
        include: "health,info"
  
  # Health check configuration
  endpoint:
    health:
      # Show basic health details
      show-details: always

# =============================================================================
# EXTERNAL API CONFIGURATION - DEVELOPMENT
# =============================================================================
external-apis:
  # TMDb API Configuration for development
  tmdb:
    # API Key for development environment
    # Set this as an environment variable: TMDB_API_KEY=your-actual-key
    # For local development, you can also create a .env file (add to .gitignore)
    apiKey: ${TMDB_API_KEY:your-tmdb-api-key-here}

# =============================================================================
# APPLICATION-SPECIFIC DEVELOPMENT SETTINGS
# =============================================================================
showsync:
  # Development-specific settings
  development:
    # Enable test data creation
    create-test-data: false
    # Enable mock external APIs
    mock-external-apis: true
    # Enhanced error messages
    detailed-error-messages: true 