# =============================================================================
# ShowSync Application Configuration
# =============================================================================
# Main configuration file for ShowSync backend service.
# This file contains common settings shared across all environments.
# Environment-specific settings are in application-{profile}.yml files.
#
# Configuration Structure:
# - Server settings (port, compression, etc.)
# - Spring Boot framework configuration
# - Database connection settings
# - Redis cache configuration
# - Security and authentication
# - API documentation settings
# - Logging configuration
# - Monitoring and health checks
# - External API configurations
# =============================================================================

# =============================================================================
# APPLICATION INFORMATION
# =============================================================================
spring:
  application:
    name: showsync-backend
    version: 0.1.0-SNAPSHOT
  
  # =============================================================================
  # PROFILE CONFIGURATION
  # =============================================================================
  profiles:
    # Default profile for local development
    # Can be overridden with --spring.profiles.active=dev/test/prod
    active: dev
  
  # =============================================================================
  # JPA & DATABASE CONFIGURATION
  # =============================================================================
  jpa:
    # Hibernate-specific settings
    hibernate:
      # Update database schema automatically in development
      # This will be overridden in production profiles
      ddl-auto: validate
      # Use new ID generator mappings
      use-new-id-generator-mappings: true
      # Naming strategy for database objects
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    
    # Show SQL statements in logs (for development/debugging)
    show-sql: false
    # Format SQL statements for readability
    properties:
      hibernate:
        format_sql: true
        # Enable SQL statement logging
        use_sql_comments: true
        # Optimize batch operations
        jdbc:
          batch_size: 25
        # Enable second-level cache
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    
    # Open EntityManager in view pattern - disabled for performance
    open-in-view: false
  
  # =============================================================================
  # DATABASE MIGRATION (FLYWAY)
  # =============================================================================
  flyway:
    # Enable Flyway database migration
    enabled: true
    # Location of migration scripts
    locations: classpath:db/migration
    # Baseline version for existing databases
    baseline-version: 1
    # Baseline on migrate for existing databases
    baseline-on-migrate: true
    # Validate migrations on startup
    validate-on-migrate: true
    # Clean database before migration (NEVER in production)
    clean-disabled: true
  
  # =============================================================================
  # CACHING CONFIGURATION
  # =============================================================================
  cache:
    # Cache type - Redis for distributed caching
    type: redis
    # Cache names to create at startup
    cache-names:
      - users
      - media
      - groups
      - recommendations
      - external-api-responses
  
  # =============================================================================
  # SECURITY CONFIGURATION
  # =============================================================================
  security:
    # JWT token configuration
    jwt:
      # Secret key for JWT signing (overridden in environment-specific configs)
      secret: changeme-in-production
      # Token expiration time (24 hours)
      expiration: 86400000
      # Refresh token expiration (7 days)
      refresh-expiration: 604800000
  
  # =============================================================================
  # JSON PROCESSING
  # =============================================================================
  jackson:
    # Serialization settings
    serialization:
      # Write dates as timestamps
      write-dates-as-timestamps: false
      # Fail on empty beans
      fail-on-empty-beans: false
    # Deserialization settings
    deserialization:
      # Don't fail on unknown properties
      fail-on-unknown-properties: false
      # Accept single value as array
      accept-single-value-as-array: true
    # Default property inclusion
    default-property-inclusion: NON_NULL
    # Time zone for date serialization
    time-zone: UTC
  
  # =============================================================================
  # ASYNC PROCESSING
  # =============================================================================
  task:
    execution:
      pool:
        # Core number of threads
        core-size: 4
        # Maximum number of threads
        max-size: 16
        # Queue capacity
        queue-capacity: 100
        # Keep alive time
        keep-alive: 60s
      # Thread name prefix
      thread-name-prefix: showsync-async-
    scheduling:
      pool:
        # Number of threads for scheduled tasks
        size: 4
      # Thread name prefix
      thread-name-prefix: showsync-scheduled-

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  # Default port (can be overridden per environment)
  port: 8080
  
  # Servlet context path
  servlet:
    context-path: /
  
  # Compression settings for better performance
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
    min-response-size: 1024
  
  # HTTP/2 support
  http2:
    enabled: true
  
  # Error handling
  error:
    # Don't include exception details in response
    include-exception: false
    # Don't include stack trace in response
    include-stacktrace: never
    # Custom error page path
    path: /error

# =============================================================================
# ACTUATOR (MONITORING & HEALTH CHECKS)
# =============================================================================
management:
  # Actuator endpoints configuration
  endpoints:
    web:
      # Base path for actuator endpoints
      base-path: /actuator
      # Expose specific endpoints
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - env
          - configprops
          - beans
          - loggers
  
  # Health check configuration
  endpoint:
    health:
      # Show detailed health information
      show-details: when-authorized
      # Health check roles
      roles: ADMIN
    # Metrics endpoint configuration
    metrics:
      enabled: true
    # Environment endpoint
    env:
      enabled: true
      # Show values for authorized users only
      show-values: when-authorized
  
  # Health indicators
  health:
    # Database health check
    db:
      enabled: true
    # Redis health check
    redis:
      enabled: true
    # Disk space health check
    diskspace:
      enabled: true
      threshold: 100MB
  
  # Metrics configuration
  metrics:
    # Enable JVM metrics
    enable:
      jvm: true
      system: true
      web: true
      
    # Metric tags to add to all metrics
    tags:
      application: showsync-backend
      environment: ${spring.profiles.active}
    
    # Distribution percentiles
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        
    # Export to Prometheus (for monitoring)
    export:
      prometheus:
        enabled: true

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  # Logging levels
  level:
    # Root logging level
    root: INFO
    
    # ShowSync application logging
    com.showsync: DEBUG
    
    # Spring framework logging
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    
    # Database logging
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
    # Redis logging
    org.springframework.data.redis: INFO
    
    # Flyway logging
    org.flywaydb: INFO
  
  # Logging pattern
  pattern:
    # Console logging pattern
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
    # File logging pattern (if file logging is enabled)
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  # Log file configuration (disabled by default, enabled per environment)
  file:
    name: logs/showsync.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB

# =============================================================================
# API DOCUMENTATION (OpenAPI/Swagger)
# =============================================================================
springdoc:
  # OpenAPI configuration
  api-docs:
    enabled: true
    path: /api-docs
  
  # Swagger UI configuration
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    # Try it out enabled by default
    try-it-out-enabled: true
    # Operations sorter
    operations-sorter: method
    # Tags sorter
    tags-sorter: alpha
    # Display request duration
    display-request-duration: true
  
  # Documentation metadata
  info:
    title: ShowSync API
    description: |
      ShowSync Backend API - AI-powered social media discovery platform for TV shows, movies, and books.
      
      This API provides endpoints for:
      - User management and authentication
      - Media library management (movies, TV shows, books)  
      - Social group management and activities
      - AI-powered group matching and content recommendations
      - Real-time communication and notifications
    version: 0.1.0-SNAPSHOT
    contact:
      name: ShowSync Development Team
      email: dev@showsync.com
      url: https://github.com/yourusername/ShowSync
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT

# =============================================================================
# EXTERNAL API CONFIGURATION
# =============================================================================
external-apis:
  # The Movie Database (TMDb) API
  tmdb:
    base-url: https://api.themoviedb.org/3
    # API key to be set in environment-specific configuration
    api-key: ${TMDB_API_KEY:}
    # Request timeout in milliseconds
    timeout: 5000
    # Rate limiting
    rate-limit:
      requests-per-second: 40
  
  # Open Library API
  open-library:
    base-url: https://openlibrary.org
    # Request timeout in milliseconds
    timeout: 10000
    # Rate limiting
    rate-limit:
      requests-per-second: 100
  
  # Google Books API
  google-books:
    base-url: https://www.googleapis.com/books/v1
    # API key to be set in environment-specific configuration
    api-key: ${GOOGLE_BOOKS_API_KEY:}
    # Request timeout in milliseconds
    timeout: 5000
    # Rate limiting
    rate-limit:
      requests-per-second: 1000

# =============================================================================
# APPLICATION-SPECIFIC CONFIGURATION
# =============================================================================
showsync:
  # AI and recommendation settings
  ai:
    # Recommendation engine settings
    recommendations:
      # Maximum number of recommendations to return
      max-results: 20
      # Minimum confidence score for recommendations
      min-confidence: 0.6
      # Cache duration for recommendations (in hours)
      cache-duration: 6
    
    # Group matching settings
    group-matching:
      # Maximum number of group recommendations
      max-group-recommendations: 10
      # Minimum compatibility score for group matching
      min-compatibility-score: 0.7
  
  # File upload settings
  upload:
    # Maximum file size for uploads
    max-file-size: 10MB
    # Allowed file types
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
  
  # Email settings (for notifications)
  email:
    # SMTP settings to be configured in environment-specific files
    enabled: false
    
  # Pagination defaults
  pagination:
    # Default page size
    default-size: 20
    # Maximum page size
    max-size: 100 